language: java
sudo: false # faster builds
jdk:
  - openjdk8

before_install:
  # If cloudpool uses a SNAPSHOT dependency of scale.commons, make sure it
  # gets built prior to running the cloudpool build.
  - git clone https://github.com/elastisys/scale.commons ~/builds/scale.commons
  - pushd ~/builds/scale.commons
  - mvn clean install -Dmaven.test.skip
  - popd 

# download dependencies: by default, runs
# "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
# which would cause Docker images to be built (and fail)
install: mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B
after_success:
  # run jacoco test coverage report and upload to codecov.io
  - mvn org.jacoco:jacoco-maven-plugin:report
  - bash <(curl -s https://codecov.io/bash)
